### ISSUE TITLE
App startet nicht mehr

### ISSUE THREAD

**Issue by oliverlorenz** [Razzeee/plugin.video.rocketbeans#3]
Hi!

Danke für dieses tolle Addon! Ich nutze es sehr oft und war bisher sehr zufrieden! Leider scheint nun irgendetwas kaputt zu sein. Die App startet leider nur noch mit einer Fehlermeldung und einem sehr generischem Screen.

Wenn man einen Blick in den Log wirft, kann man folgende Fehlermeldung erkennen, mit der ich aber nicht viel anfangen kann :confused: 

```
2019-04-26 08:46:33.762 T:1758458592   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object is not iterable
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.rocketbeans/addon.py", line 4, in <module>
                                                plugin.run()
                                              File "/home/osmc/.kodi/addons/plugin.video.rocketbeans/resources/lib/plugin.py", line 167, in run
                                                plugin.run()
                                              File "/home/osmc/.kodi/addons/script.module.routing/lib/routing.py", line 115, in run
                                                self._dispatch(path)
                                              File "/home/osmc/.kodi/addons/script.module.routing/lib/routing.py", line 126, in _dispatch
                                                view_func(**kwargs)
                                              File "/home/osmc/.kodi/addons/plugin.video.rocketbeans/resources/lib/plugin.py", line 34, in index
                                                livestream_url, livestream_thumbnail, title = get_livestream()
                                              File "/home/osmc/.kodi/addons/plugin.video.rocketbeans/resources/lib/plugin.py", line 29, in get_livestream
                                                livestream_url, title, livestream_thumbnail = YoutubeStream().get_live_video_info_from_channel_id(config.CHANNEL_ID)
                                              File "/home/osmc/.kodi/addons/plugin.video.rocketbeans/resources/lib/youtube.py", line 11, in get_live_video_info_from_channel_id
                                                video_id, title = self.get_video_info(request)
                                            TypeError: 'NoneType' object is not iterable
                                            -->End of Python script error report<--
2019-04-26 08:46:34.026 T:1428148960   ERROR: GetDirectory - Error getting plugin://plugin.video.rocketbeans/
2019-04-26 08:46:34.036 T:1915975216   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.rocketbeans/) failed
```

Disablen/Enabled, Deinstallieren und wieder installieren haben leider nicht geholfen. Hast du eine Idee was ich noch tun kann?

**Comment by Khazaa** [comment]
In den Settings von Youtube auf Twitch umstellen, dann geht es erstmal wieder..

**Comment by Khazaa** [comment]
Trotzdem sollte das Problem gelöst werden.
So wie ich das sehe, kommt der Titel vom Youtube-Video nicht (oder falsch/unlesbar) zurück und daher der Fehler. Das bekomme ich leider nicht gefixt (zu wenig Erfahrung mit den Add-Ons), sonst würd ich einen Pull-Request machen.

**Comment by Razzeee** [comment]
Sorry, youtube hat sich geaendert.

Hier is der fix https://github.com/Razzeee/plugin.video.rocketbeans/commit/0f2de7a37add12157b22ac31f101c427e10cb545

Sehe zu das das schnell ins repo kommt.

**Comment by oliverlorenz** [comment]
@Khazaa
> In den Settings von Youtube auf Twitch umstellen, dann geht es erstmal wieder..

Danke! Das Löst das Problem schon mal aus User-Sicht  :slightly_smiling_face: 

Danke auch an @Razzeee für den generellen Bugfix :slightly_smiling_face:
